=== ivanm06/retoeval2/web/xsd/establecimiento.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="establecimientos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="establecimiento" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="id" type="xs:int" />
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="localizacion" type="xs:string" />
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ivanm06/retoeval2/web/establecimiento.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./xsl/establecimiento.xsl" type="text/xsl"?>
<establecimientos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="./xsd/establecimiento.xsd">
    <establecimiento>
        <id>1</id>
        <nombre>Tienda Paco</nombre>
        <localizacion>Calle cuatrocientos 34s</localizacion>
        <imagen>/images/establecimiento1.jpg</imagen>
    </establecimiento>
    <establecimiento>
        <id>2</id>
        <nombre>Tienda Pacos</nombre>
        <localizacion>Calles cuatrocientos 34s</localizacion>
        <imagen>/images/establecimiento1.jpg</imagen>
    </establecimiento>
</establecimientos>
